**Importing necessary libraries**

In [ ]:
pip install --pre pycaret

Collecting pycaret
  Downloading pycaret-3.0.0rc9-py3-none-any.whl (480 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.1/480.1 kB 5.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: tqdm>=4.62.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (4.62.3)
Collecting tbats>=1.1.0
  Downloading tbats-1.1.2-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 1.6 MB/s eta 0:00:00
Collecting kaleido>=0.2.1
  Downloading kaleido-0.2.1-py2.py3-none-macosx_10_11_x86_64.whl (85.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 MB 10.5 MB/s eta 0:00:0000:0100:01
Collecting pmdarima!=1.8.1,<3.0.0,>=1.8.0
  Downloading pmdarima-2.0.2-cp39-cp39-macosx_10_9_x86_64.whl (608 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.3/608.3 kB 9.5 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: ipython>=5.5.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (7.29.0)
Requirement already satisfied: statsmodels>=0.12.1 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (0.12.2)
Collecting sktime>=0.15.0
  Downloading sktime-0.16.1-py3-none-any.whl (16.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 12.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: plotly>=5.0.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (5.6.0)
Requirement already satisfied: scipy<2.0.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.7.1)
Requirement already satisfied: pandas<1.6.0,>=1.3.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.3.4)
Collecting schemdraw>=0.14
  Downloading schemdraw-0.15-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 3.7 MB/s eta 0:00:00
Collecting plotly-resampler>=0.7.2.2
  Downloading plotly_resampler-0.8.4rc1.tar.gz (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 1.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Requested plotly-resampler>=0.7.2.2 from https://files.pythonhosted.org/packages/d7/5e/71a9e34a36c1855d0c4e30a88405d58c4bbbe7ece802b188628a643f2cda/plotly_resampler-0.8.4rc1.tar.gz#sha256=154ebffa9778813fe457ac9112e71e085ac283644a1e26b869bd5c6b7bf064a2 (from pycaret), but installing version 0.8.4rc1
Requirement already satisfied: lightgbm>=3.0.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (3.3.3)
Collecting deprecation>=2.1.0
  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting imbalanced-learn>=0.8.1
  Downloading imbalanced_learn-0.10.1-py3-none-any.whl (226 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.0/226.0 kB 6.2 MB/s eta 0:00:00
Collecting numpy<1.25,>=1.21
  Downloading numpy-1.24.2-cp39-cp39-macosx_10_9_x86_64.whl (19.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 11.8 MB/s eta 0:00:0000:0100:01
Collecting requests>=2.27.1
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: ipywidgets>=7.6.5 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (7.6.5)
Collecting pyod>=0.9.8
  Using cached pyod-1.0.7.tar.gz (147 kB)
  Preparing metadata (setup.py) ... done
Collecting scikit-plot>=0.3.7
  Using cached scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Requirement already satisfied: matplotlib>=3.3.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (3.4.3)
Collecting numba>=0.55.0
  Downloading numba-0.56.4-cp39-cp39-macosx_10_14_x86_64.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 5.1 MB/s eta 0:00:0000:0100:01m
Collecting markupsafe>=2.0.1
  Downloading MarkupSafe-2.1.2-cp39-cp39-macosx_10_9_x86_64.whl (13 kB)
Collecting yellowbrick>=1.4
  Using cached yellowbrick-1.5-py3-none-any.whl (282 kB)
Requirement already satisfied: jinja2>=1.2 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (2.11.3)
Requirement already satisfied: cloudpickle in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (2.0.0)
Collecting scikit-learn>=1.0
  Downloading scikit_learn-1.2.1-cp39-cp39-macosx_10_9_x86_64.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 12.7 MB/s eta 0:00:0000:0100:01
Collecting joblib>=1.2.0
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 7.3 MB/s eta 0:00:0000:01
Collecting category-encoders>=2.4.0
  Downloading category_encoders-2.6.0-py2.py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 3.2 MB/s eta 0:00:00
Collecting xxhash
  Downloading xxhash-3.2.0-cp39-cp39-macosx_10_9_x86_64.whl (35 kB)
Requirement already satisfied: nbformat>=4.2.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (5.1.3)
Collecting importlib-metadata>=4.12.0
  Downloading importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
Collecting psutil>=5.9.0
  Downloading psutil-5.9.4-cp36-abi3-macosx_10_9_x86_64.whl (243 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.5/243.5 kB 6.4 MB/s eta 0:00:00
Requirement already satisfied: patsy>=0.5.1 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from category-encoders>=2.4.0->pycaret) (0.5.2)
Requirement already satisfied: packaging in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from deprecation>=2.1.0->pycaret) (21.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from imbalanced-learn>=0.8.1->pycaret) (2.2.0)
Requirement already satisfied: zipp>=0.5 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from importlib-metadata>=4.12.0->pycaret) (3.6.0)
Requirement already satisfied: decorator in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (5.1.0)
Requirement already satisfied: appnope in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.1.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (3.0.20)
Requirement already satisfied: backcall in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (5.1.0)
Requirement already satisfied: setuptools>=18.5 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (58.0.4)
Requirement already satisfied: pygments in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (2.10.0)
Requirement already satisfied: matplotlib-inline in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.1.2)
Requirement already satisfied: jedi>=0.16 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.18.0)
Requirement already satisfied: pickleshare in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.7.5)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (1.0.0)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (6.4.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (3.5.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.0)

Requirement already satisfied: wheel in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from lightgbm>=3.0.0->pycaret) (0.37.0)
Requirement already satisfied: cycler>=0.10 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->pycaret) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->pycaret) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->pycaret) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->pycaret) (9.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->pycaret) (1.3.1)
Requirement already satisfied: jupyter-core in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from nbformat>=4.2.0->pycaret) (4.11.2)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from nbformat>=4.2.0->pycaret) (3.2.0)
Collecting llvmlite<0.40,>=0.39.0dev0
  Downloading llvmlite-0.39.1-cp39-cp39-macosx_10_9_x86_64.whl (25.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.5/25.5 MB 11.7 MB/s eta 0:00:0000:0100:01
Collecting numpy<1.25,>=1.21
  Downloading numpy-1.23.5-cp39-cp39-macosx_10_9_x86_64.whl (18.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 13.3 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pytz>=2017.3 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pandas<1.6.0,>=1.3.0->pycaret) (2021.3)
Requirement already satisfied: six in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from plotly>=5.0.0->pycaret) (1.16.0)
Requirement already satisfied: tenacity>=6.2.0 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from plotly>=5.0.0->pycaret) (8.0.1)
Collecting jupyter-dash>=0.4.2
  Downloading jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
Collecting pandas<1.6.0,>=1.3.0
  Downloading pandas-1.5.3-cp39-cp39-macosx_10_9_x86_64.whl (12.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 13.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: Werkzeug<=2.1.2 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from plotly-resampler>=0.7.2.2->pycaret) (2.0.2)
Collecting dash<3.0.0,>=2.2.0
  Downloading dash-2.8.1-py3-none-any.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 14.0 MB/s eta 0:00:0000:0100:01
Collecting orjson<4.0.0,>=3.8.0
  Downloading orjson-3.8.7-cp39-cp39-macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl (489 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.3/489.3 kB 8.9 MB/s eta 0:00:0000:01
Collecting Flask-Cors<4.0.0,>=3.0.10
  Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting trace-updater>=0.0.8
  Downloading trace_updater-0.0.9-py3-none-any.whl (185 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.1/185.1 kB 5.8 MB/s eta 0:00:00
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (0.29.24)
Requirement already satisfied: urllib3 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (1.26.7)
Collecting statsmodels>=0.12.1
  Downloading statsmodels-0.13.5-cp39-cp39-macosx_10_9_x86_64.whl (9.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 13.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: certifi>=2017.4.17 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.27.1->pycaret) (2022.6.15)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.27.1->pycaret) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/purushottamgupta/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.27.1->pycaret) (3.2)
Collecting numpy<1.25,>=1.21
  Downloading numpy-1.22.4-cp39-cp39-macosx_10_15_x86_64.whl (17.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━ 14.2/17.7 MB 13.1 MB/s eta 0:00:01

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
from pycaret.datasets import get_data
from pycaret.anomaly import *
mpl.rcParams['figure.dpi'] = 300

ModuleNotFoundError: No module named 'pycaret'

**Loading the Dataset**

In [2]:
numeric = ['Fresh','Milk','Grocery','Frozen','Detergents_Paper','Delicassen']
categorical = ['Channel','Region']

replace_dict = { "Channel": {1: "Horeca", 2: "Retail"},
                 "Region":  {1: "Lisbon", 2: "Oporto", 3: "Other"} }

data = get_data('wholesale', verbose = False)
data.replace(replace_dict, inplace = True) 
data.head(10)

NameError: name 'get_data' is not defined

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    object
 1   Region            440 non-null    object
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicassen        440 non-null    int64
dtypes: int64(6), object(2)
memory usage: 27.6+ KB

**Initializing the Pycaret Environment**

In [4]:
anomaly = setup(data, silent = True , session_id = 8477)

                               Description                 Value
0                               session_id                  8477
1                            Original Data              (440, 8)
2                           Missing Values                 False
3                         Numeric Features                     6
4                     Categorical Features                     2
5                         Ordinal Features                 False
6                High Cardinality Features                 False
7                  High Cardinality Method                  None
8                         Transformed Data             (440, 11)
9                                 CPU Jobs                    -1
10                                 Use GPU                 False
11                          Log Experiment                 False
12                         Experiment Name  anomaly-default-name
13                                     USI                  f873
14                         Imputation Type                simple
15          Iterative Imputation Iteration                  None
16                         Numeric Imputer                  mean
17      Iterative Imputation Numeric Model                  None
18                     Categorical Imputer                  mode
19  Iterative Imputation Categorical Model                  None
20           Unknown Categoricals Handling        least_frequent
21                               Normalize                 False
22                        Normalize Method                  None
23                          Transformation                 False
24                   Transformation Method                  None
25                                     PCA                 False
26                              PCA Method                  None
27                          PCA Components                  None
28                     Ignore Low Variance                 False
29                     Combine Rare Levels                 False
30                    Rare Level Threshold                  None
31                         Numeric Binning                 False
32                         Remove Outliers                 False
33                      Outliers Threshold                  None
34                Remove Multicollinearity                 False
35             Multicollinearity Threshold                  None
36             Remove Perfect Collinearity                 False
37                              Clustering                 False
38                    Clustering Iteration                  None
39                     Polynomial Features                 False
40                       Polynomial Degree                  None
41                    Trignometry Features                 False
42                    Polynomial Threshold                  None
43                          Group Features                 False
44                       Feature Selection                 False
45                Feature Selection Method               classic
46            Features Selection Threshold                  None
47                     Feature Interaction                 False
48                           Feature Ratio                 False
49                   Interaction Threshold                  None

INFO:logs:create_model_container: 0
INFO:logs:master_model_container: 0
INFO:logs:display_container: 1
INFO:logs:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=False, features_todrop=[],
                                      id_columns=[], ml_usecase='regression',
                                      numerical_features=[],
                                      target='UNSUPERVISED_DUMMY_TARGET',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='most frequent',
                                fill_value_categorical=None,
                                fill_value_numerical=Non...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='UNSUPERVISED_DUMMY_TARGET')),
                ('fix_perfect', 'passthrough'),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
INFO:logs:setup() succesfully completed......................................

**MODEL I - Create Local Outlier Factor model with an outlier proportion of 10% and assign it to model variable**

In [5]:
model = create_model('lof', fraction = 0.10)

INFO:logs:create_model_container: 1
INFO:logs:master_model_container: 1
INFO:logs:display_container: 2
INFO:logs:LOF(algorithm='auto', contamination=0.1, leaf_size=30, metric='minkowski',
  metric_params=None, n_jobs=-1, n_neighbors=20, novelty=True, p=2)
INFO:logs:create_model() succesfully completed......................................

**Assign anomaly labels and scores to the data_assigned variable**

In [6]:
data_assigned = assign_model(model)
data_assigned.head(10)

INFO:logs:Initializing assign_model()
INFO:logs:assign_model(model=LOF(algorithm='auto', contamination=0.1, leaf_size=30, metric='minkowski',
  metric_params=None, n_jobs=-1, n_neighbors=20, novelty=True, p=2), transformation=False, score=True, verbose=True)
INFO:logs:Checking exceptions
INFO:logs:Determining Trained Model
INFO:logs:Trained Model : Local Outlier Factor
INFO:logs:Copying data
INFO:logs:(440, 10)
INFO:logs:assign_model() succesfully completed......................................

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
0,Retail,Other,12669,9656,7561,214,2674,1338,0,1.107687
1,Retail,Other,7057,9810,9568,1762,3293,1776,0,1.027102
2,Retail,Other,6353,8808,7684,2405,3516,7844,0,1.398439
3,Horeca,Other,13265,1196,4221,6404,507,1788,0,1.200384
4,Retail,Other,22615,5410,7198,3915,1777,5185,0,1.164052
5,Retail,Other,9413,8259,5126,666,1795,1451,0,1.184313
6,Retail,Other,12126,3199,6975,480,3140,545,0,1.130491
7,Retail,Other,7579,4956,9426,1669,3321,2566,0,1.013751
8,Horeca,Other,5963,3648,6192,425,1716,750,0,1.201904
9,Retail,Other,6006,11093,18881,1159,7425,2098,0,1.053333

**Create new dataset of outliers named data_outliers**

In [7]:
data_inliers = data_assigned.query('Anomaly == 0')
data_outliers = data_assigned.query('Anomaly == 1')

**Print first 5 instances of the outlier dataset**

In [8]:
data_outliers.head(5)

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
17,Horeca,Other,5876,6157,2933,839,370,4478,1,1.458161
23,Retail,Other,26373,36423,22019,5154,4337,16523,1,2.249573
47,Retail,Other,44466,54259,55571,7782,24171,6465,1,3.224197
56,Retail,Other,4098,29892,26866,2616,17740,1340,1,1.529652
61,Retail,Other,35942,38369,59598,3254,26701,2017,1,2.799411

****MODEL II - Create Angle Based Outlier Detection Model with an outlier proportion of 10% and assign it to model variable****

In [17]:
abod = create_model('abod', fraction = 0.1)

INFO:logs:create_model_container: 4
INFO:logs:master_model_container: 4
INFO:logs:display_container: 5
INFO:logs:ABOD(contamination=0.1, method='fast', n_neighbors=5)
INFO:logs:create_model() succesfully completed......................................

**Assign anomaly labels and scores to the data_assigned variable**

In [18]:
data_assigned = assign_model(abod)
data_assigned.head(10)

INFO:logs:Initializing assign_model()
INFO:logs:assign_model(model=ABOD(contamination=0.1, method='fast', n_neighbors=5), transformation=False, score=True, verbose=True)
INFO:logs:Checking exceptions
INFO:logs:Determining Trained Model
INFO:logs:Trained Model : Angle-base Outlier Detection
INFO:logs:Copying data
INFO:logs:(440, 10)
INFO:logs:assign_model() succesfully completed......................................

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
0,Retail,Other,12669,9656,7561,214,2674,1338,0,-5.664321e-16
1,Retail,Other,7057,9810,9568,1762,3293,1776,0,-1.723476e-15
2,Retail,Other,6353,8808,7684,2405,3516,7844,0,-3.949764e-17
3,Horeca,Other,13265,1196,4221,6404,507,1788,0,-1.465539e-15
4,Retail,Other,22615,5410,7198,3915,1777,5185,0,-2.898443e-16
5,Retail,Other,9413,8259,5126,666,1795,1451,0,-4.686618e-16
6,Retail,Other,12126,3199,6975,480,3140,545,0,-1.068663e-15
7,Retail,Other,7579,4956,9426,1669,3321,2566,0,-2.604080e-15
8,Horeca,Other,5963,3648,6192,425,1716,750,0,-5.329998e-15
9,Retail,Other,6006,11093,18881,1159,7425,2098,0,-1.170233e-15

**Create new dataset of outliers named data_outliers**

In [19]:
data_inliers = data_assigned.query('Anomaly == 0')
data_outliers = data_assigned.query('Anomaly == 1')

**Print first 5 instances of the outlier dataset**

In [20]:
data_outliers.head(5)

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
23,Retail,Other,26373,36423,22019,5154,4337,16523,1,-4.124038e-20
39,Horeca,Other,56159,555,902,10002,212,2916,1,-2.620307e-17
45,Retail,Other,5181,22044,21531,1740,7353,4985,1,-3.469083e-17
47,Retail,Other,44466,54259,55571,7782,24171,6465,1,-7.848229e-20
56,Retail,Other,4098,29892,26866,2616,17740,1340,1,-1.134013e-17

**MODEL III - Create iForest Model with an outlier proportion of 10% and assign it to model variable**

In [21]:
iforest = create_model('iforest', fraction = 0.1)

INFO:logs:create_model_container: 5
INFO:logs:master_model_container: 5
INFO:logs:display_container: 6
INFO:logs:IForest(behaviour='new', bootstrap=False, contamination=0.1, max_features=1.0,
    max_samples='auto', n_estimators=100, n_jobs=-1, random_state=8477,
    verbose=0)
INFO:logs:create_model() succesfully completed......................................

**Assign anomaly labels and scores to the data_assigned variable**

In [22]:
data_assigned = assign_model(iforest)
data_assigned.head(10)

INFO:logs:Initializing assign_model()
INFO:logs:assign_model(model=IForest(behaviour='new', bootstrap=False, contamination=0.1, max_features=1.0,
    max_samples='auto', n_estimators=100, n_jobs=-1, random_state=8477,
    verbose=0), transformation=False, score=True, verbose=True)
INFO:logs:Checking exceptions
INFO:logs:Determining Trained Model
INFO:logs:Trained Model : Isolation Forest
INFO:logs:Copying data
INFO:logs:(440, 10)
INFO:logs:assign_model() succesfully completed......................................

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
0,Retail,Other,12669,9656,7561,214,2674,1338,0,-0.124265
1,Retail,Other,7057,9810,9568,1762,3293,1776,0,-0.130061
2,Retail,Other,6353,8808,7684,2405,3516,7844,0,-0.059521
3,Horeca,Other,13265,1196,4221,6404,507,1788,0,-0.154400
4,Retail,Other,22615,5410,7198,3915,1777,5185,0,-0.046611
5,Retail,Other,9413,8259,5126,666,1795,1451,0,-0.121751
6,Retail,Other,12126,3199,6975,480,3140,545,0,-0.115792
7,Retail,Other,7579,4956,9426,1669,3321,2566,0,-0.127756
8,Horeca,Other,5963,3648,6192,425,1716,750,0,-0.161993
9,Retail,Other,6006,11093,18881,1159,7425,2098,0,-0.125618

**Create new dataset of outliers named data_outliers**

In [23]:
data_inliers = data_assigned.query('Anomaly == 0')
data_outliers = data_assigned.query('Anomaly == 1')

**Print first 5 instances of the outlier dataset**

In [24]:
data_outliers.head(5)

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
23,Retail,Other,26373,36423,22019,5154,4337,16523,1,0.094344
47,Retail,Other,44466,54259,55571,7782,24171,6465,1,0.167576
61,Retail,Other,35942,38369,59598,3254,26701,2017,1,0.113484
65,Retail,Other,85,20959,45828,36,24231,1423,1,0.043013
71,Horeca,Other,18291,1266,21042,5373,4173,14472,1,0.031175

**MODEL IV - Create SVM with an outlier proportion of 10% and assign it to model variable**

In [39]:
svm = create_model('svm',)

INFO:logs:create_model_container: 12
INFO:logs:master_model_container: 12
INFO:logs:display_container: 13
INFO:logs:OCSVM(cache_size=200, coef0=0.0, contamination=0.05, degree=3, gamma='auto',
   kernel='rbf', max_iter=-1, nu=0.5, shrinking=True, tol=0.001,
   verbose=False)
INFO:logs:create_model() succesfully completed......................................

**Assign anomaly labels and scores to the data_assigned variable**

In [40]:
data_assigned = assign_model(svm)
data_assigned.head(10)

INFO:logs:Initializing assign_model()
INFO:logs:assign_model(model=OCSVM(cache_size=200, coef0=0.0, contamination=0.05, degree=3, gamma='auto',
   kernel='rbf', max_iter=-1, nu=0.5, shrinking=True, tol=0.001,
   verbose=False), transformation=False, score=True, verbose=True)
INFO:logs:Checking exceptions
INFO:logs:Determining Trained Model
INFO:logs:Trained Model : One-class SVM detector
INFO:logs:Copying data
INFO:logs:(440, 10)
INFO:logs:assign_model() succesfully completed......................................

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
0,Retail,Other,12669,9656,7561,214,2674,1338,0,-0.0
1,Retail,Other,7057,9810,9568,1762,3293,1776,0,-0.0
2,Retail,Other,6353,8808,7684,2405,3516,7844,0,-0.0
3,Horeca,Other,13265,1196,4221,6404,507,1788,0,-0.0
4,Retail,Other,22615,5410,7198,3915,1777,5185,0,-0.0
5,Retail,Other,9413,8259,5126,666,1795,1451,0,-0.0
6,Retail,Other,12126,3199,6975,480,3140,545,0,-0.0
7,Retail,Other,7579,4956,9426,1669,3321,2566,0,-0.0
8,Horeca,Other,5963,3648,6192,425,1716,750,0,-0.0
9,Retail,Other,6006,11093,18881,1159,7425,2098,0,-0.0

**Create new dataset of outliers named data_outliers**

In [41]:
data_inliers = data_assigned.query('Anomaly == 0')
data_outliers = data_assigned.query('Anomaly == 1')

**Print first 5 instances of the outlier dataset**

In [42]:
data_outliers.head(5)

Empty DataFrame
Columns: [Channel, Region, Fresh, Milk, Grocery, Frozen, Detergents_Paper, Delicassen, Anomaly, Anomaly_Score]
Index: []

**MODEL V - Create KNN with an outlier proportion of 10% and assign it to model variable**

In [29]:
knn = create_model('knn', fraction = 0.1)

INFO:logs:create_model_container: 9
INFO:logs:master_model_container: 9
INFO:logs:display_container: 10
INFO:logs:KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
  radius=1.0)
INFO:logs:create_model() succesfully completed......................................

**Assign anomaly labels and scores to the data_assigned variable**

In [30]:
data_assigned = assign_model(knn)
data_assigned.head(10)

INFO:logs:Initializing assign_model()
INFO:logs:assign_model(model=KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
  radius=1.0), transformation=False, score=True, verbose=True)
INFO:logs:Checking exceptions
INFO:logs:Determining Trained Model
INFO:logs:Trained Model : K-Nearest Neighbors Detector
INFO:logs:Copying data
INFO:logs:(440, 10)
INFO:logs:assign_model() succesfully completed......................................

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
0,Retail,Other,12669,9656,7561,214,2674,1338,0,4412.718437
1,Retail,Other,7057,9810,9568,1762,3293,1776,0,3893.808419
2,Retail,Other,6353,8808,7684,2405,3516,7844,0,6837.430877
3,Horeca,Other,13265,1196,4221,6404,507,1788,0,3621.922694
4,Retail,Other,22615,5410,7198,3915,1777,5185,0,5769.670874
5,Retail,Other,9413,8259,5126,666,1795,1451,0,4412.718437
6,Retail,Other,12126,3199,6975,480,3140,545,0,3802.832365
7,Retail,Other,7579,4956,9426,1669,3321,2566,0,3465.169837
8,Horeca,Other,5963,3648,6192,425,1716,750,0,2814.278238
9,Retail,Other,6006,11093,18881,1159,7425,2098,0,5012.273137

**Create new dataset of outliers named data_outliers**

In [31]:
data_inliers = data_assigned.query('Anomaly == 0')
data_outliers = data_assigned.query('Anomaly == 1')

**Print first 5 instances of the outlier dataset**

In [32]:
data_outliers.head(5)

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
23,Retail,Other,26373,36423,22019,5154,4337,16523,1,29286.316515
39,Horeca,Other,56159,555,902,10002,212,2916,1,11788.374358
45,Retail,Other,5181,22044,21531,1740,7353,4985,1,9341.904035
47,Retail,Other,44466,54259,55571,7782,24171,6465,1,50651.461104
49,Retail,Other,4967,21412,28921,1798,13583,1163,1,9557.434070