In [ ]:
# 1)	Load the dataset wholsale from the pycaret package

In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import matplotlib as mpl
import seaborn as sns
from pycaret.datasets import get_data 
from pycaret.anomaly import * 
mpl.rcParams['figure.dpi'] = 300
# Loading Dataset
numeric = ['Fresh','Milk','Grocery','Frozen','Detergents_Paper','Delicassen']
categorical = ['Channel','Region']
replace_dict = { "Channel": {1: "Horeca", 2: "Retail"},
                 "Region":  {1: "Lisbon", 2: "Oporto", 3: "Other"} }
data = get_data('wholesale', verbose = False)
data.replace(replace_dict, inplace = True)
# PyCaret environment setup
anomaly = setup(data, silent=True, session_id = 8477)

                               Description                 Value
0                               session_id                  8477
1                            Original Data              (440, 8)
2                           Missing Values                 False
3                         Numeric Features                     6
4                     Categorical Features                     2
5                         Ordinal Features                 False
6                High Cardinality Features                 False
7                  High Cardinality Method                  None
8                         Transformed Data             (440, 11)
9                                 CPU Jobs                    -1
10                                 Use GPU                 False
11                          Log Experiment                 False
12                         Experiment Name  anomaly-default-name
13                                     USI                  de64
14                         Imputation Type                simple
15          Iterative Imputation Iteration                  None
16                         Numeric Imputer                  mean
17      Iterative Imputation Numeric Model                  None
18                     Categorical Imputer                  mode
19  Iterative Imputation Categorical Model                  None
20           Unknown Categoricals Handling        least_frequent
21                               Normalize                 False
22                        Normalize Method                  None
23                          Transformation                 False
24                   Transformation Method                  None
25                                     PCA                 False
26                              PCA Method                  None
27                          PCA Components                  None
28                     Ignore Low Variance                 False
29                     Combine Rare Levels                 False
30                    Rare Level Threshold                  None
31                         Numeric Binning                 False
32                         Remove Outliers                 False
33                      Outliers Threshold                  None
34                Remove Multicollinearity                 False
35             Multicollinearity Threshold                  None
36             Remove Perfect Collinearity                 False
37                              Clustering                 False
38                    Clustering Iteration                  None
39                     Polynomial Features                 False
40                       Polynomial Degree                  None
41                    Trignometry Features                 False
42                    Polynomial Threshold                  None
43                          Group Features                 False
44                       Feature Selection                 False
45                Feature Selection Method               classic
46            Features Selection Threshold                  None
47                     Feature Interaction                 False
48                           Feature Ratio                 False
49                   Interaction Threshold                  None

INFO:logs:create_model_container: 0
INFO:logs:master_model_container: 0
INFO:logs:display_container: 1
INFO:logs:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=False, features_todrop=[],
                                      id_columns=[], ml_usecase='regression',
                                      numerical_features=[],
                                      target='UNSUPERVISED_DUMMY_TARGET',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='most frequent',
                                fill_value_categorical=None,
                                fill_value_numerical=Non...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='UNSUPERVISED_DUMMY_TARGET')),
                ('fix_perfect', 'passthrough'),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
INFO:logs:setup() succesfully completed......................................

In [45]:
data.head(5)

  Channel Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0  Retail  Other  12669  9656     7561     214              2674        1338
1  Retail  Other   7057  9810     9568    1762              3293        1776
2  Retail  Other   6353  8808     7684    2405              3516        7844
3  Horeca  Other  13265  1196     4221    6404               507        1788
4  Retail  Other  22615  5410     7198    3915              1777        5185

In [ ]:
#!pip install pycaret

In [ ]:
#!pip install numba==0.53

# Local Outlier Factor Model

In [22]:
# 2)	Create a Local Outlier Factor model with an outlier proportion of 10% and assign it to model variable
model = create_model('lof', fraction = 0.1)

INFO:logs:create_model_container: 3
INFO:logs:master_model_container: 3
INFO:logs:display_container: 4
INFO:logs:LOF(algorithm='auto', contamination=0.1, leaf_size=30, metric='minkowski',
  metric_params=None, n_jobs=-1, n_neighbors=20, novelty=True, p=2)
INFO:logs:create_model() succesfully completed......................................

In [23]:
# 3)	Assign anomaly labels and scores to the data_assigned variable
data_assigned = assign_model(model)
data_assigned.head(10)

INFO:logs:Initializing assign_model()
INFO:logs:assign_model(model=LOF(algorithm='auto', contamination=0.1, leaf_size=30, metric='minkowski',
  metric_params=None, n_jobs=-1, n_neighbors=20, novelty=True, p=2), transformation=False, score=True, verbose=True)
INFO:logs:Checking exceptions
INFO:logs:Determining Trained Model
INFO:logs:Trained Model : Local Outlier Factor
INFO:logs:Copying data
INFO:logs:(440, 10)
INFO:logs:assign_model() succesfully completed......................................

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
0,Retail,Other,12669,9656,7561,214,2674,1338,0,1.107687
1,Retail,Other,7057,9810,9568,1762,3293,1776,0,1.027102
2,Retail,Other,6353,8808,7684,2405,3516,7844,0,1.398439
3,Horeca,Other,13265,1196,4221,6404,507,1788,0,1.200384
4,Retail,Other,22615,5410,7198,3915,1777,5185,0,1.164052
5,Retail,Other,9413,8259,5126,666,1795,1451,0,1.184313
6,Retail,Other,12126,3199,6975,480,3140,545,0,1.130491
7,Retail,Other,7579,4956,9426,1669,3321,2566,0,1.013751
8,Horeca,Other,5963,3648,6192,425,1716,750,0,1.201904
9,Retail,Other,6006,11093,18881,1159,7425,2098,0,1.053333

In [24]:
# 4)	Create new dataset of outliers named data_outliers
data_inliers = data_assigned.query('Anomaly == 0')
data_outliers = data_assigned.query('Anomaly == 1')

In [25]:
# 5)	Print first 5 instances of the outlier dataset
data_outliers.head(5)

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
17,Horeca,Other,5876,6157,2933,839,370,4478,1,1.458161
23,Retail,Other,26373,36423,22019,5154,4337,16523,1,2.249573
47,Retail,Other,44466,54259,55571,7782,24171,6465,1,3.224197
56,Retail,Other,4098,29892,26866,2616,17740,1340,1,1.529652
61,Retail,Other,35942,38369,59598,3254,26701,2017,1,2.799411

# SVM

In [46]:
# 2)	Create a Local Outlier Factor model with an outlier proportion of 10% and assign it to model variable
model = create_model('svm', fraction = 0.1)

INFO:logs:create_model_container: 9
INFO:logs:master_model_container: 9
INFO:logs:display_container: 10
INFO:logs:OCSVM(cache_size=200, coef0=0.0, contamination=0.1, degree=3, gamma='auto',
   kernel='rbf', max_iter=-1, nu=0.5, shrinking=True, tol=0.001,
   verbose=False)
INFO:logs:create_model() succesfully completed......................................

In [47]:
# 3)	Assign anomaly labels and scores to the data_assigned variable
data_assigned = assign_model(model)
data_assigned.head(10)

INFO:logs:Initializing assign_model()
INFO:logs:assign_model(model=OCSVM(cache_size=200, coef0=0.0, contamination=0.1, degree=3, gamma='auto',
   kernel='rbf', max_iter=-1, nu=0.5, shrinking=True, tol=0.001,
   verbose=False), transformation=False, score=True, verbose=True)
INFO:logs:Checking exceptions
INFO:logs:Determining Trained Model
INFO:logs:Trained Model : One-class SVM detector
INFO:logs:Copying data
INFO:logs:(440, 10)
INFO:logs:assign_model() succesfully completed......................................

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
0,Retail,Other,12669,9656,7561,214,2674,1338,0,-0.0
1,Retail,Other,7057,9810,9568,1762,3293,1776,0,-0.0
2,Retail,Other,6353,8808,7684,2405,3516,7844,0,-0.0
3,Horeca,Other,13265,1196,4221,6404,507,1788,0,-0.0
4,Retail,Other,22615,5410,7198,3915,1777,5185,0,-0.0
5,Retail,Other,9413,8259,5126,666,1795,1451,0,-0.0
6,Retail,Other,12126,3199,6975,480,3140,545,0,-0.0
7,Retail,Other,7579,4956,9426,1669,3321,2566,0,-0.0
8,Horeca,Other,5963,3648,6192,425,1716,750,0,-0.0
9,Retail,Other,6006,11093,18881,1159,7425,2098,0,-0.0

In [48]:
# 4)	Create new dataset of outliers named data_outliers
data_inliers = data_assigned.query('Anomaly == 0')
data_outliers = data_assigned.query('Anomaly == 1')

In [49]:
# 5)	Print first 5 instances of the outlier dataset
data_outliers.head(5)

Empty DataFrame
Columns: [Channel, Region, Fresh, Milk, Grocery, Frozen, Detergents_Paper, Delicassen, Anomaly, Anomaly_Score]
Index: []

# ABOD

In [33]:
# 2)	Create a Local Outlier Factor model with an outlier proportion of 10% and assign it to model variable
model = create_model('abod', fraction = 0.1)

INFO:logs:create_model_container: 6
INFO:logs:master_model_container: 6
INFO:logs:display_container: 7
INFO:logs:ABOD(contamination=0.1, method='fast', n_neighbors=5)
INFO:logs:create_model() succesfully completed......................................

In [34]:
# 3)	Assign anomaly labels and scores to the data_assigned variable
data_assigned = assign_model(model)
data_assigned.head(10)

INFO:logs:Initializing assign_model()
INFO:logs:assign_model(model=ABOD(contamination=0.1, method='fast', n_neighbors=5), transformation=False, score=True, verbose=True)
INFO:logs:Checking exceptions
INFO:logs:Determining Trained Model
INFO:logs:Trained Model : Angle-base Outlier Detection
INFO:logs:Copying data
INFO:logs:(440, 10)
INFO:logs:assign_model() succesfully completed......................................

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
0,Retail,Other,12669,9656,7561,214,2674,1338,0,-5.664321e-16
1,Retail,Other,7057,9810,9568,1762,3293,1776,0,-1.723476e-15
2,Retail,Other,6353,8808,7684,2405,3516,7844,0,-3.949764e-17
3,Horeca,Other,13265,1196,4221,6404,507,1788,0,-1.465539e-15
4,Retail,Other,22615,5410,7198,3915,1777,5185,0,-2.898443e-16
5,Retail,Other,9413,8259,5126,666,1795,1451,0,-4.686618e-16
6,Retail,Other,12126,3199,6975,480,3140,545,0,-1.068663e-15
7,Retail,Other,7579,4956,9426,1669,3321,2566,0,-2.604080e-15
8,Horeca,Other,5963,3648,6192,425,1716,750,0,-5.329998e-15
9,Retail,Other,6006,11093,18881,1159,7425,2098,0,-1.170233e-15

In [35]:
# 4)	Create new dataset of outliers named data_outliers
data_inliers = data_assigned.query('Anomaly == 0')
data_outliers = data_assigned.query('Anomaly == 1')

In [36]:
# 5)	Print first 5 instances of the outlier dataset
data_outliers.head(5)

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
23,Retail,Other,26373,36423,22019,5154,4337,16523,1,-4.124038e-20
39,Horeca,Other,56159,555,902,10002,212,2916,1,-2.620307e-17
45,Retail,Other,5181,22044,21531,1740,7353,4985,1,-3.469083e-17
47,Retail,Other,44466,54259,55571,7782,24171,6465,1,-7.848229e-20
56,Retail,Other,4098,29892,26866,2616,17740,1340,1,-1.134013e-17

# IForest

In [37]:
# 2)	Create a Local Outlier Factor model with an outlier proportion of 10% and assign it to model variable
model = create_model('iforest', fraction = 0.1)

INFO:logs:create_model_container: 7
INFO:logs:master_model_container: 7
INFO:logs:display_container: 8
INFO:logs:IForest(behaviour='new', bootstrap=False, contamination=0.1, max_features=1.0,
    max_samples='auto', n_estimators=100, n_jobs=-1, random_state=8477,
    verbose=0)
INFO:logs:create_model() succesfully completed......................................

In [38]:
# 3)	Assign anomaly labels and scores to the data_assigned variable
data_assigned = assign_model(model)
data_assigned.head(10)

INFO:logs:Initializing assign_model()
INFO:logs:assign_model(model=IForest(behaviour='new', bootstrap=False, contamination=0.1, max_features=1.0,
    max_samples='auto', n_estimators=100, n_jobs=-1, random_state=8477,
    verbose=0), transformation=False, score=True, verbose=True)
INFO:logs:Checking exceptions
INFO:logs:Determining Trained Model
INFO:logs:Trained Model : Isolation Forest
INFO:logs:Copying data
INFO:logs:(440, 10)
INFO:logs:assign_model() succesfully completed......................................

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
0,Retail,Other,12669,9656,7561,214,2674,1338,0,-0.124265
1,Retail,Other,7057,9810,9568,1762,3293,1776,0,-0.130061
2,Retail,Other,6353,8808,7684,2405,3516,7844,0,-0.059521
3,Horeca,Other,13265,1196,4221,6404,507,1788,0,-0.154400
4,Retail,Other,22615,5410,7198,3915,1777,5185,0,-0.046611
5,Retail,Other,9413,8259,5126,666,1795,1451,0,-0.121751
6,Retail,Other,12126,3199,6975,480,3140,545,0,-0.115792
7,Retail,Other,7579,4956,9426,1669,3321,2566,0,-0.127756
8,Horeca,Other,5963,3648,6192,425,1716,750,0,-0.161993
9,Retail,Other,6006,11093,18881,1159,7425,2098,0,-0.125618

In [39]:
# 4)	Create new dataset of outliers named data_outliers
data_inliers = data_assigned.query('Anomaly == 0')
data_outliers = data_assigned.query('Anomaly == 1')

In [40]:
# 5)	Print first 5 instances of the outlier dataset
data_outliers.head(5)

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
23,Retail,Other,26373,36423,22019,5154,4337,16523,1,0.094344
47,Retail,Other,44466,54259,55571,7782,24171,6465,1,0.167576
61,Retail,Other,35942,38369,59598,3254,26701,2017,1,0.113484
65,Retail,Other,85,20959,45828,36,24231,1423,1,0.043013
71,Horeca,Other,18291,1266,21042,5373,4173,14472,1,0.031175

# KNN

In [41]:
# 2)	Create a Local Outlier Factor model with an outlier proportion of 10% and assign it to model variable
model = create_model('knn', fraction = 0.1)

INFO:logs:create_model_container: 8
INFO:logs:master_model_container: 8
INFO:logs:display_container: 9
INFO:logs:KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
  radius=1.0)
INFO:logs:create_model() succesfully completed......................................

In [42]:
# 3)	Assign anomaly labels and scores to the data_assigned variable
data_assigned = assign_model(model)
data_assigned.head(10)

INFO:logs:Initializing assign_model()
INFO:logs:assign_model(model=KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
  radius=1.0), transformation=False, score=True, verbose=True)
INFO:logs:Checking exceptions
INFO:logs:Determining Trained Model
INFO:logs:Trained Model : K-Nearest Neighbors Detector
INFO:logs:Copying data
INFO:logs:(440, 10)
INFO:logs:assign_model() succesfully completed......................................

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
0,Retail,Other,12669,9656,7561,214,2674,1338,0,4412.718437
1,Retail,Other,7057,9810,9568,1762,3293,1776,0,3893.808419
2,Retail,Other,6353,8808,7684,2405,3516,7844,0,6837.430877
3,Horeca,Other,13265,1196,4221,6404,507,1788,0,3621.922694
4,Retail,Other,22615,5410,7198,3915,1777,5185,0,5769.670874
5,Retail,Other,9413,8259,5126,666,1795,1451,0,4412.718437
6,Retail,Other,12126,3199,6975,480,3140,545,0,3802.832365
7,Retail,Other,7579,4956,9426,1669,3321,2566,0,3465.169837
8,Horeca,Other,5963,3648,6192,425,1716,750,0,2814.278238
9,Retail,Other,6006,11093,18881,1159,7425,2098,0,5012.273137

In [43]:
# 4)	Create new dataset of outliers named data_outliers
data_inliers = data_assigned.query('Anomaly == 0')
data_outliers = data_assigned.query('Anomaly == 1')

In [44]:
# 5)	Print first 5 instances of the outlier dataset
data_outliers.head(5)

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,Anomaly,Anomaly_Score
23,Retail,Other,26373,36423,22019,5154,4337,16523,1,29286.316515
39,Horeca,Other,56159,555,902,10002,212,2916,1,11788.374358
45,Retail,Other,5181,22044,21531,1740,7353,4985,1,9341.904035
47,Retail,Other,44466,54259,55571,7782,24171,6465,1,50651.461104
49,Retail,Other,4967,21412,28921,1798,13583,1163,1,9557.434070